FROM grafana/grafana:12.3.0-18578466485

COPY ./datasources /etc/grafana/provisioning/datasources
COPY ./dashboards /etc/grafana/provisioning/dashboards
COPY ./krakend /var/lib/grafana/dashboards/krakend